// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using teste_mysql_do_zero.Contexts;

#nullable disable

namespace teste_mysql_do_zero.Migrations
{
    [DbContext(typeof(BancoAnimeContext))]
    [Migration("20220519175706_gerar_tabela_animes")]
    partial class gerar_tabela_animes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("teste_mysql_do_zero.Models.Entities.AnimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeAnime")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Anime", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
